type GuitarString = { Note: string; Octave: int; Gauge: float }

let low = { Note = "E"; Octave = 2; Gauge = 0.046 } // the labels tell F# the type
let high = { low with Octave = 4; Gauge = 0.010 } // copy and update, like with in C#

printfn "%s%d, gauge %.3f" low.Note low.Octave low.Gauge
printfn "%A" high

// Structural equality and comparison, generated by the compiler
printfn "%b" (high = { Note = "E"; Octave = 4; Gauge = 0.010 })
printfn "%b" (low = high)
printfn "%b" (low < high) // fields compared in order: Note, then Octave
