#!/usr/bin/env bash
# Music theory for Guitar Alchemist: fetch the pinned GA projects, build the course program
# and compare each lesson's output and diagrams with the expected ones
set -euo pipefail
cd "$(dirname "$0")"
bash fetch-ga.sh
dotnet build GaTheory -c Release -m:4 --nologo -v quiet
status=0
for lesson in l1 l2 l3 l4 l5 l6 l7; do
  if dotnet run --project GaTheory -c Release --no-build -- "$lesson" | diff --strip-trailing-cr "expected/$lesson.txt" -; then
    echo "ok   $lesson"
  else
    echo "FAIL $lesson"
    status=1
  fi
done
# the diagrams of the lessons are generated by the same program: the committed SVG files must be up to date
if dotnet run --project GaTheory -c Release --no-build -- svg ../../src/assets/music-theory-ga --check; then
  echo "ok   svg"
else
  echo "FAIL svg: run  dotnet run --project code/music-theory-ga/GaTheory -c Release -- svg src/assets/music-theory-ga"
  status=1
fi
exit $status
