// Labels of the bookmarks and notes, by the page's language (the lang attribute Starlight puts on <html>)

const en = {
	bookmarkPage: 'Bookmark this page',
	bookmarked: 'Bookmarked',
	unbookmarkPage: 'Remove this page from my bookmarks',
	bookmarkSection: 'Bookmark the section',
	unbookmarkSection: 'Remove the section from my bookmarks',
	quote: ['“', '”'],
	notes: 'My notes',
	notesTitle: 'My notes on this page',
	notesPlaceholder: 'Write down what you want to remember. Your notes stay in this browser.',
	savedAt: 'Saved at',
	notSaved: 'Not saved: this browser blocks local storage.',
	library: 'All my bookmarks and notes',
	bookmarks: 'Bookmarks',
	noBookmarks: 'No bookmarks yet. Use the bookmark button above a lesson, or the one next to a section heading.',
	noNotes: 'No notes yet. Each lesson has a notes box at the bottom.',
	export: 'Export',
	import: 'Import',
	clear: 'Delete everything',
	confirmClear: 'Delete all your bookmarks and notes from this browser?',
	confirmDeleteNote: 'Delete this note?',
	remove: 'Remove',
	imported: 'Imported: {bookmarks} bookmarks and {notes} notes.',
	importFailed: 'This file is not an export of bookmarks and notes.',
	added: 'Added',
	updated: 'Updated',
	storageBlocked: 'This browser blocks local storage (private window or blocked site data), so bookmarks and notes can’t be kept.',
};

type Strings = typeof en;

const fr: Strings = {
	bookmarkPage: 'Ajouter cette page à mes favoris',
	bookmarked: 'Dans mes favoris',
	unbookmarkPage: 'Retirer cette page de mes favoris',
	bookmarkSection: 'Ajouter à mes favoris la section',
	unbookmarkSection: 'Retirer de mes favoris la section',
	quote: ['« ', ' »'],
	notes: 'Mes notes',
	notesTitle: 'Mes notes sur cette page',
	notesPlaceholder: 'Notez ce que vous voulez retenir. Vos notes restent dans ce navigateur.',
	savedAt: 'Enregistré à',
	notSaved: 'Non enregistré : ce navigateur bloque le stockage local.',
	library: 'Tous mes favoris et notes',
	bookmarks: 'Favoris',
	noBookmarks: 'Aucun favori pour l’instant. Utilisez le bouton favori au-dessus d’une leçon, ou celui à côté d’un titre de section.',
	noNotes: 'Aucune note pour l’instant. Chaque leçon a un bloc de notes en bas de page.',
	export: 'Exporter',
	import: 'Importer',
	clear: 'Tout supprimer',
	confirmClear: 'Supprimer de ce navigateur tous vos favoris et toutes vos notes ?',
	confirmDeleteNote: 'Supprimer cette note ?',
	remove: 'Retirer',
	imported: 'Importé : {bookmarks} favoris et {notes} notes.',
	importFailed: 'Ce fichier n’est pas un export de favoris et de notes.',
	added: 'Ajouté le',
	updated: 'Modifié le',
	storageBlocked: 'Ce navigateur bloque le stockage local (fenêtre privée ou données de site bloquées) : les favoris et les notes ne peuvent pas être gardés.',
};

const es: Strings = {
	bookmarkPage: 'Añadir esta página a mis marcadores',
	bookmarked: 'En mis marcadores',
	unbookmarkPage: 'Quitar esta página de mis marcadores',
	bookmarkSection: 'Añadir a mis marcadores la sección',
	unbookmarkSection: 'Quitar de mis marcadores la sección',
	quote: ['«', '»'],
	notes: 'Mis notas',
	notesTitle: 'Mis notas sobre esta página',
	notesPlaceholder: 'Anote lo que quiera recordar. Sus notas se quedan en este navegador.',
	savedAt: 'Guardado a las',
	notSaved: 'No guardado: este navegador bloquea el almacenamiento local.',
	library: 'Todos mis marcadores y notas',
	bookmarks: 'Marcadores',
	noBookmarks: 'Todavía no hay marcadores. Use el botón de marcador encima de una lección, o el que está junto al título de una sección.',
	noNotes: 'Todavía no hay notas. Cada lección tiene un bloque de notas al final.',
	export: 'Exportar',
	import: 'Importar',
	clear: 'Borrar todo',
	confirmClear: '¿Borrar de este navegador todos sus marcadores y notas?',
	confirmDeleteNote: '¿Borrar esta nota?',
	remove: 'Quitar',
	imported: 'Importado: {bookmarks} marcadores y {notes} notas.',
	importFailed: 'Este archivo no es una exportación de marcadores y notas.',
	added: 'Añadido el',
	updated: 'Modificado el',
	storageBlocked: 'Este navegador bloquea el almacenamiento local (ventana privada o datos del sitio bloqueados), así que los marcadores y las notas no se pueden guardar.',
};

export function readerStrings(lang: string): Strings {
	return lang.startsWith('fr') ? fr : lang.startsWith('es') ? es : en;
}
