// Lesson 19: one typed function per Rust command. The types come from ts-rs
// (src/bindings, generated by `cargo test`); the command names and argument names
// are still strings that TypeScript cannot check against the Rust code.
import { Channel, invoke } from "@tauri-apps/api/core";
import type { ChordView } from "./bindings/ChordView";
import type { CommandError } from "./bindings/CommandError";
import type { QualityView } from "./bindings/QualityView";
import type { ScaleMode } from "./bindings/ScaleMode";
import type { SearchEvent } from "./bindings/SearchEvent";

export const chordQualities = () => invoke<QualityView[]>("chord_qualities");

export const spellChord = (symbol: string) => invoke<ChordView>("spell_chord", { symbol });

export const transposeChord = (symbol: string, semitones: number) =>
  invoke<ChordView>("transpose_chord", { symbol, semitones });

export const diatonicChords = (tonicNote: string, mode: ScaleMode) =>
  invoke<ChordView[]>("diatonic_chords", { tonicNote, mode });

export const favorites = () => invoke<string[]>("favorites");

export const toggleFavorite = (symbol: string) => invoke<string[]>("toggle_favorite", { symbol });

export function findVoicings(symbol: string, maxSpan: number, onEvent: (event: SearchEvent) => void) {
  const channel = new Channel<SearchEvent>();
  channel.onmessage = onEvent;
  return invoke<number>("find_voicings", { symbol, maxSpan, onEvent: channel });
}

export const cancelSearch = () => invoke<void>("cancel_search");

// A rejected invoke gives a CommandError, or a string when Tauri itself refuses the call
export function isCommandError(error: unknown): error is CommandError {
  return typeof error === "object" && error !== null && "kind" in error && "message" in error;
}

export function describe(error: unknown): string {
  return isCommandError(error) ? `${error.kind}: ${error.message}` : String(error);
}
