"""Resolve the internal links of the built site, the way a browser would, and report those that 404.

Reading the Markdown is not enough. A link written `../artifacts/` looks right in the source and can land
on a page that does not exist, because the site is served under a `base` prefix and a page's depth in the
URL is not its depth in `src/content/docs/`. Grepping the built HTML for the href is not enough either:
the string is there, and wrong. So each href is joined onto the URL of the page that carries it, and the
result is looked up in `dist/`, fragment included.

Run it after `npm run build`:

    python scripts/check-links.py                  # every built page
    python scripts/check-links.py blender/journal  # only these pages
    python scripts/check-links.py --self-test      # prove the check can fail

Only the links inside the article are checked; the navigation and the sidebar are generated by Starlight.
Exits non-zero as soon as one link does not resolve.
"""
from __future__ import annotations

import argparse
import html as html_mod
import re
import sys
import urllib.parse
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CONTENT = '<div class="sl-markdown-content">'
HREF = re.compile(r'<a\s[^>]*?href="([^"]+)"')   # links the reader can follow, not stylesheets
ID = re.compile(r'\sid="([^"]+)"')


def site_base() -> str:
    """The `base` of astro.config.mjs, without its trailing slash: the pages are served under it."""
    m = re.search(r"base:\s*['\"]([^'\"]*)['\"]", (REPO / "astro.config.mjs").read_text(encoding="utf-8"))
    return (m.group(1) if m else "").rstrip("/")


class Site:
    def __init__(self, dist: Path, base: str) -> None:
        self.dist, self.base, self.ids = dist, base, {}

    def anchors(self, url_path: str) -> set[str] | None:
        """The ids of the page at this URL path, or None when nothing is served there.

        A file that is not HTML — a stylesheet, an image, a zip — answers with an empty set: it exists,
        and it has no anchors to check.
        """
        if url_path in self.ids:
            return self.ids[url_path]
        rest = url_path[len(self.base):].lstrip("/")
        self.ids[url_path] = None
        for candidate in (self.dist / rest / "index.html", self.dist / rest, self.dist / (rest + ".html")):
            if candidate.is_file():
                text = candidate.read_text(encoding="utf-8", errors="ignore") \
                    if candidate.suffix in (".html", "") else ""
                self.ids[url_path] = set(ID.findall(text))
                break
        return self.ids[url_path]

    def check(self, page: str, html: str) -> list[str]:
        """`page` is the page's own URL path; returns one line per link that does not resolve."""
        broken, seen = [], set()
        for raw in HREF.findall(html.split(CONTENT, 1)[-1]):
            href = html_mod.unescape(raw)          # an href in the source reads &amp; for &
            if href.startswith(("http://", "https://", "mailto:", "//")) or href in seen:
                continue
            seen.add(href)
            url = urllib.parse.urljoin(page, href)
            path, _, fragment = url.partition("#")
            path = path.partition("?")[0]          # a query selects a state of the page, not a page
            ids = self.anchors(path)
            if ids is None:
                broken.append(f"{href} -> {url} (no page there)")
            elif fragment and urllib.parse.unquote(fragment) not in ids:
                broken.append(f"{href} -> {url} (no such anchor on that page)")
        return broken


def self_test(site: Site, page: str) -> int:
    """A check that has never failed is a decoration: give it a broken link and watch it fail."""
    html = CONTENT + '<a href="../no-such-page/">x</a><a href="#no-such-anchor">y</a>'
    broken = site.check(page, html)
    print("\n".join("  " + b for b in broken))
    if len(broken) == 2:
        print("self-test: the check reports both broken links")
        return 0
    print(f"self-test FAILED: expected 2 broken links, got {len(broken)}")
    return 1


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pages", nargs="*", help="page URL paths under the base, e.g. fr/blender/journal")
    ap.add_argument("--dist", default="dist", help="the built site (default: dist)")
    ap.add_argument("--self-test", action="store_true", help="check that the check can fail, then stop")
    args = ap.parse_args()

    dist = Path(args.dist) if Path(args.dist).is_absolute() else REPO / args.dist
    if not dist.is_dir():
        sys.exit(f"{dist} does not exist: run npm run build first")
    base = site_base()
    site = Site(dist, base)

    files = [dist / (p.strip("/") + "/index.html") for p in args.pages] if args.pages \
        else sorted(dist.rglob("index.html"))
    if args.self_test:
        sys.exit(self_test(site, f"{base}/{files[0].parent.relative_to(dist).as_posix()}/"))

    total = 0
    for f in files:
        if not f.is_file():
            sys.exit(f"{f} does not exist")
        page = f"{base}/{f.parent.relative_to(dist).as_posix()}/".replace("/./", "/")
        broken = site.check(page, f.read_text(encoding="utf-8"))
        total += len(broken)
        for b in broken:
            print(f"{page}: {b}")
    print(f"{len(files)} page(s), {total} link(s) that do not resolve")
    sys.exit(1 if total else 0)


if __name__ == "__main__":
    main()
