package dev.learn.spring.l05;

import io.r2dbc.h2.H2ConnectionConfiguration;
import io.r2dbc.h2.H2ConnectionFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate;
import reactor.test.StepVerifier;

import static org.assertj.core.api.Assertions.assertThat;

class VoicingCatalogTest {
    private R2dbcEntityTemplate template;
    private VoicingCatalog catalog;

    @BeforeEach
    void setUp() {
        var connectionFactory = new H2ConnectionFactory(H2ConnectionConfiguration.builder()
                .inMemory("lesson05-" + System.nanoTime())
                .property("DB_CLOSE_DELAY", "-1")
                .build());
        template = new R2dbcEntityTemplate(connectionFactory);
        catalog = new VoicingCatalog(template);
        template.getDatabaseClient().sql("""
                CREATE TABLE "voicing" (
                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SYMBOL" VARCHAR(32) NOT NULL,
                    "FRET" INTEGER NOT NULL
                )
                """).then().block();
    }

    @Test
    void insertsAndStreamsMatchingRowsWithoutBlockingInThePipeline() {
        var result = catalog.save(Voicing.newVoicing("Cmaj7", 3))
                .then(catalog.save(Voicing.newVoicing("Dm7", 5)))
                .thenMany(catalog.findBySymbol("Cmaj7"));

        StepVerifier.create(result)
                .assertNext(voicing -> {
                    assertThat(voicing.id()).isPositive();
                    assertThat(voicing.symbol()).isEqualTo("Cmaj7");
                    assertThat(voicing.fret()).isEqualTo(3);
                })
                .verifyComplete();
    }

    @Test
    void aTransactionIsAReactiveBoundary() {
        StepVerifier.create(template.getDatabaseClient()
                        .inConnection(connection -> reactor.core.publisher.Mono.from(connection.beginTransaction())
                                .then(reactor.core.publisher.Mono.from(connection.createStatement(
                                        "INSERT INTO \"voicing\"(\"SYMBOL\", \"FRET\") VALUES ('G7', 7)").execute()))
                                .then(reactor.core.publisher.Mono.from(connection.rollbackTransaction()))
                                .thenReturn("rolled back")))
                .expectNext("rolled back")
                .verifyComplete();

        StepVerifier.create(catalog.findBySymbol("G7"))
                .verifyComplete();
    }
}
