// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The error a failed command sends to the frontend, where the promise rejects with
 * `{ kind, message }`.
 */
export type CommandError = { kind: string, message: string, };
