// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quality for the frontend's help list.
 */
export type QualityView = { suffix: string, name: string, };
